name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source repository
        uses: actions/checkout@v4
        with:
          path: source-repo

      - name: Create and checkout pages repository
        run: |
          # Clone the pages repository (this might fail if repo is empty, that's ok)
          git clone https://${{ secrets.DEPLOY_TOKEN }}@github.com/shahinabdi/shahinabdi.github.io.git pages-repo || mkdir pages-repo
          cd pages-repo
          
          # Initialize if it's empty
          if [ ! -d .git ]; then
            git init
            git remote add origin https://${{ secrets.DEPLOY_TOKEN }}@github.com/shahinabdi/shahinabdi.github.io.git
          fi
          
          # Create and checkout main branch
          git checkout main 2>/dev/null || git checkout -b main
          
          # Clean directory but keep .git
          find . -mindepth 1 -maxdepth 1 ! -name '.git' -exec rm -rf {} +
          
          # Create .nojekyll file
          touch .nojekyll

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: source-repo/package-lock.json

      - name: Install dependencies
        working-directory: source-repo
        run: npm ci

      - name: Build project
        working-directory: source-repo
        run: npm run build

      - name: Copy build files
        run: |
          cp -r source-repo/dist/* pages-repo/

      - name: Deploy to GitHub Pages
        working-directory: pages-repo
        run: |
          git config user.name "GitHub Actions"
          git config user.email "github-actions@github.com"
          git add .
          git commit -m "Deploy React application" || echo "No changes to commit"
          git remote set-url origin https://${{ secrets.DEPLOY_TOKEN }}@github.com/shahinabdi/shahinabdi.github.io.git
          git push -u origin main -f